"""add_llmops_tables

Revision ID: 27d35334ab83
Revises: ec84bc25d7b4
Create Date: 2026-06-14 11:18:26.361086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d35334ab83'
down_revision: Union[str, Sequence[str], None] = 'ec84bc25d7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_a', sa.String(length=100), nullable=False),
    sa.Column('model_b', sa.String(length=100), nullable=False),
    sa.Column('prompt_a_id', sa.UUID(), nullable=True),
    sa.Column('prompt_b_id', sa.UUID(), nullable=True),
    sa.Column('traffic_split_a', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_a_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_b_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analytics_logs', sa.Column('experiment_id', sa.UUID(), nullable=True))
    op.add_column('analytics_logs', sa.Column('variant', sa.String(length=50), nullable=True))
    
    op.add_column('messages', sa.Column('experiment_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('variant', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'variant')
    op.drop_column('messages', 'experiment_id')
    op.drop_column('analytics_logs', 'variant')
    op.drop_column('analytics_logs', 'experiment_id')
    op.drop_table('experiments')
    op.drop_table('prompts')
    # ### end Alembic commands ###
